name: Fetch Live Games

on:
  workflow_dispatch:    # allows manual runs
  schedule:
    - cron: '0 5 * * *'  # runs once per day at 5:00 UTC

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Fetch live games
        run: python fetch_live_games.py
      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add live_games.json
          git commit -m "Update live games"
          git push
