name: "Fetch Today's Games"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'   # At 05:00 UTC every day

jobs:
  fetch:
    runs-on: ubuntu-latest

    env:
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      GH_PAT:      ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug environment variables
        run: |
          echo "RAPIDAPI_KEY=${RAPIDAPI_KEY:0:4}****"
          echo "GH_PAT=${GH_PAT:0:4}****"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch live games
        run: npm run fetch-live-games
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          GH_PAT:      ${{ secrets.GH_PAT }}

      - name: Commit and push updates
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/live-games.json
          git commit -m "Update live games data"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
